services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017" 

    volumes:
      - mongo-data:/data/db
  node:
    build:
      context: backend-API
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000" 
    volumes:
      - ./backend-API/:/app
    env_file:
      - backend-API/.env
    environment:
      MONGO_URL: mongodb://mongo:27017
      # MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    restart: unless-stopped
  vite:
    build:
      context: admin-dashboard
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - admin-dashboard/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173" 
    depends_on:
      - node
    volumes:
      - /app/node_modules
      - ./admin-dashboard/:/app
    restart: unless-stopped

volumes:
  mongo-data:
