name: CI/CD Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #   DEPLOY FRONTEND
      - name: Sync frontend to VPS
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude=".git" --exclude="node_modules" --exclude="mongo-data" --exclude="admin-dashboard/.env" --exclude="backend-API/.env"
          path: admin-dashboard/
          remote_path: ${{ secrets.VPS_PATH }}/admin-dashboard/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22

      #   DEPLOY BACKEND
      - name: Sync backend to VPS
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude=".git" --exclude="node_modules" --exclude="mongo-data" --exclude="admin-dashboard/.env" --exclude="backend-API/.env"
          path: backend-API/
          remote_path: ${{ secrets.VPS_PATH }}/backend-API/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22

      #  RESTART SERVICES (SSH)
      - name: Restart application on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/project/API_Jeu
            
            #  FRONTEND .ENV
            echo "Recreating admin-dashboard .env"
            cat > admin-dashboard/.env << EOF
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            EOF

            #  BACKEND .ENV
            echo "Recreating backend-API .env"
            cat > backend-API/.env << EOF
            MONGO_URL=${{ secrets.MONGO_URL }}
            appName=${{ secrets.APPNAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_expiresIn=${{ secrets.JWT_EXPIRESIN }}
            EOF

            #  RESTART DOCKER
            echo "Restarting docker containers..."
            docker compose -f compose.prod.yml down
            docker compose -f compose.prod.yml up -d --build
