name: CI/CD Deploy

on:
  push:
    branches:
      - feature/gitaction

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      # - name: Build frontend
      #   run: |
      #     cd admin-dashboard
      #     npm ci
      #     npm run build

      - name: Sync frontend build to VPS
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: >
            -avzr 
            --delete
            --exclude=".git"
            --exclude="node_modules"
            --exclude="mongo-data"
            --exclude="admin-dashboard/.env"
            --exclude="backend-API/.env"
          path: admin-dashboard/
          remote_path: ${{ secrets.VPS_PATH }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22

      - name: Restart application on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/project/API_Jeu
            docker compose -f compose.prod.yml down
            docker compose -f compose.prod.yml up -d --build

